const orientations = [
    {
        "name":'Heterosexual',
        "weight":{
            "stat":94,
            "statplus":80,
            "equal":1,
            "maxrep":0,
            "bipan":2
        }
    },
    {
        "name":'Homosexual',
        "weight":{
            "stat":2,
            "statplus":5,
            "equal":1,
            "maxrep":25,
            "bipan":2
        }
    },
    {
        "name":'Bisexual',
        "weight":{
            "stat":1.5,
            "statplus":5,
            "equal":1,
            "maxrep":25,
            "bipan":47
        },
        "variations":['','','','','','slight male preference','slight female preference','strong male preference','strong female preference']
    },
    {
        "name":'Pansexual',
        "weight":{
            "stat":1.5,
            "statplus":5,
            "equal":1,
            "maxrep":25,
            "bipan":47
        }
    },
    {
        "name":'Asexual',
        "weight":{
            "stat":1,
            "statplus":5,
            "equal":1,
            "maxrep":25,
            "bipan":2
        },
        "variations":['heteroromantic','homoromantic','biromantic','panromantic','aromantic','demisexual']
    }
]