const worshipStyles = [
    "Worships","Worships","Worships","Worships","Worships",
    "Follows","Follows","Follows","Follows","Follows","Follows",
    "Acknowledges","Acknowledges",
    "Honors","Honors","Honors","Honors","Honors","Honors","Honors",
    "Prays to","Prays to","Prays to","Prays to","Prays to",
    "Sometimes prays to","Sometimes prays to","Sometimes prays to",
    "Casually worships","Casually worships","Casually worships",
    "Adheres to the culture around, but not the religion of,",
    "Blessed by",
    "Makes offerings to","Makes offerings to","Makes offerings to",
    "Drawn to",
    "Seeks the approval of",
    "Seeks forgiveness from",
    "Seeks power from",
    "Adores",
    "Fanatically worships",
    "Is a servant of",
    "Is an acolyte of",
    "Follows the teachings of",
    "Considering worshipping",
    "Devoutly worships","Devoutly worships","Devoutly worships",
    "Is devoted to"
]

const religionsByCulture = [
    ["The majority religion in their culture",15],
    ["A minority religion in their culture",5],
    ["A religion from a local culture that's not their own",3],
    ["A religion from a far-away culture that's not their own",1],
    ["The ancient folk religion of their ancestors",2],
    ["A lost religion of another culture",1],
    ["A newly formed religion or cult",1],
    ["Combines beliefs from multiple religions",2],
    ["A religion of their own creation",1],
    ["Non-Religious",10]
]

const religionsByStructure = [
    ["Monotheism (worships one god, rejects all others)",1],
    ["Henotheism (worships one god of a pantheon, respects the others)",15],
    ["Polytheism (worships multiple gods of a pantheon)",10],
    ["Animism (worships the spiritual essence in all things, often involves nature spirits)",3],
    ["Nontheism (follows a spiritual philosophy without worshipping any gods)",3],
    ["Agnosticism (ambivalent towards gods, does not actively follow a religion)",10],
    ["Atheism (actively rejects the gods)",1]
]

const religionsByDomain = ['Air','Animal','Arcana','Avarice','Balance','Beasts','Change','Chaos','Charity','Charm','Chastity','Civilization','Cold','Community','Corruption','Craft','Creation','Darkness','Death','Demonic','Destruction','Diabolic','Dream','Drow','Dwarf','Earth','Elf','Endurance','Envy','Evil','Family','Fate','Fey','Fire','Forge','Freedom','Generosity','Glory','Gluttony','Gnome','Good','Grave','Greed','Hatred','Healing','Hope','Humility','Illusion','Joy','Justice','Knowledge','Law','Life','Light','Love','Luck','Lust','Madness','Magic','Metal','Mind','Moon','Nature','Nobility','Ocean','Order','Pain','Patience','Planning','Plant','Pleasure','Poison','Pride','Protection','Renewal','Repose','Retribution','Rune','Sea','Skill','Slime','Sloth','Spiders','Storm','Strength','Strife','Suffering','Sun','Temperance','Tempest','Time','Torment','Trade','Travel','Trickery','Tyranny','Undeath','Underdark','Vengeance','War','Water','Wilderness','Winter','Wrath','Zeal'];

const religionsBySetting = [
    {
        "name":"Forgotten Realms",
        "pre":"fr",
        "gods":[ 
            "Auril, goddess of winter",
            "Azuth, god of wizards",
            "Bane, god of tyranny",
            "Beshaba, goddess of misfortune",
            "Bhaal, god of murder",
            "Chauntea, goddess of agriculture",
            "Cyric, god of lies",
            "Deneir, god of writing",
            "Eldath, goddess of peace",
            "Gond, god of craft",
            "Helm, god of protection",
            "Ilmater, god of endurance",
            "Kelemvor, god of the dead",
            "Lathander, god of birth and renewal",
            "Leira, goddess of illusion",
            "Lliira, goddess of joy",
            "Loviatar, goddess of pain",
            "Malar, god of the hunt",
            "Mask, god of thieves",
            "Mielikki, goddess of forests",
            "Milil, god of poetry and song",
            "Myrkul, god of death",
            "Mystra, goddess of magic",
            "Oghma, god of knowledge",
            "Savras, god of divination and fate",
            "Selûne, goddess of the moon",
            "Shar, goddess of darkness and loss",
            "Silvanus, god of wild nature",
            "Sune, goddess of love and beauty",
            "Talona, goddess of disease and poison",
            "Talos, god of storms",
            "Tempus, god of war",
            "Torm, god of courage and self-sacrifice",
            "Tymora, goddess of good fortune",
            "Tyr, god of justice",
            "Umberlee, goddess of the sea",
            "Waukeen, goddess of trade",
            "Bahamut, dragon god of good",
            "Blibdoolpoolp, kuo-toa goddess",
            "Corellon Larethian, elf deity of art and magic",
            "Deep Sashelas, elf god of the sea",
            "Eadro, merfolk deity of the sea",
            "Garl Glittergold, gnome god of trickery and wiles",
            "Grolantor, hill giant god of war",
            "Gruumsh, orc god of storms and war",
            "Hruggek, bugbear god of violence",
            "Kurtulmak, kobold god of war and mining",
            "Laogzed, troglodyte god of hunger",
            "Lolth, drow goddess of spiders",
            "Maglubiyet, goblinoid god of war",
            "Moradin, dwarf god of creation",
            "Rillifane Rallathil, wood elf god of nature",
            "Sehanine Moonbow, elf goddess of the moon",
            "Sekolah, sahuagin god of the hunt",
            "Semuanya, lizardfolk deity of survival",
            "Skerrit, centaur and satyr god of nature",
            "Skoraeus Stonebones, god of stone giants and art",
            "Surtur, god of fire giants and craft",
            "Thrym, god of frost giants and strength",
            "Tiamat, dragon goddess of evil",
            "Yondalla, halfling goddess of fertility and protection",
        ]
    },
    {
        "name":"Eberron",
        "pre":"eberron",
        "gods":[ 
            "Arawai, goddess of fertility",
            "Aureon, god of law and knowledge",
            "Balinor, god of beasts and the hunt",
            "Boldrei, goddess of community and home",
            "Dol Arrah, goddess of sunlight and honor",
            "Dol Dorn, god of strength at arms",
            "Kol Korran, god of trade and wealth",
            "Olladra, goddess of good fortune",
            "Onatar, god of craft",
            "The Devourer, god of nature's wrath",
            "The Fury, goddess of wrath and madness",
            "The Keeper, god of greed and death",
            "The Mockery, god of violence and treachery",
            "The Shadow, god of dark magic",
            "The Traveler, deity of chaos and change",
            "The Silver Flame, deity of protection and good",
            "The Blood of Vol, philosophy of immortality and undeath",
            "Cults of the Dragon Below, deities of madness",
            "The Path of Light, philosophy of light and self-improvement",
            "The Undying Court, elven ancestors",
            "The Spirits of the Past, elven ancestors"
        ]
    },
    {
        "name":"Greyhawk",
        "pre":"greyhawk",
        "gods":[ 
            "Beory, goddess of nature",
            "Boccob, god of magic",
            "Celestian, god of stars and wanderers",
            "Ehlonna, goddess of woodlands",
            "Erythnul, god of envy and slaughter",
            "Fharlanghn, god of horizons and travel",
            "Heironeous, god of chivalry and valor",
            "Hextor, god of war and discord",
            "Kord, god of athletics and sport",
            "Incabulos, god of plague and famine",
            "Istus, goddess of fate and destiny",
            "Iuz, god of pain and oppression",
            "Nerull, god of death",
            "Obad-Hai, god of nature",
            "Olidammara, god of revelry",
            "Pelor, god of the sun and healing",
            "Pholtus, god of light and law",
            "Ralishaz, god of ill luck and insanity",
            "Rao, god of peace and reason",
            "St. Cuthbert, god of common sense and zeal",
            "Tharizdun, god of eternal darkness",
            "Trithereon, god of liberty and retribution",
            "Ulaa, goddess of hills and mountains",
            "Vecna, god of evil secrets",
            "Wee Jas, goddess of magic and death",
        ]
    },
    {
        "name":"Dragonlance",
        "pre":"dragonlance",
        "gods":[ 
            "Paladine, god of rulers and guardians",
            "Branchala, god of music",
            "Habbakuk, god of animal life and the sea",
            "Kiri-Jolith, god of honor and war",
            "Majere, god of meditation and order",
            "Mishakal, goddess of healing",
            "Solinari, god of good magic",
            "Gilean, god of knowledge",
            "Chislev, goddess of nature",
            "Reorx, god of craft",
            "Shinare, goddess of wealth and trade",
            "Sirrion, god of fire and change",
            "Zivilyn, god of wisdom",
            "Lunitari, goddess of neutral magic",
            "Takhisis, goddess of night and hatred",
            "Chemosh, god of the undead",
            "Hiddukel, god of lies and greed",
            "Morgion, god of disease and secrecy",
            "Sargonnas, god of vengeance and fire",
            "Zeboim, goddess of the sea and storms",
            "Nuitari, god of evil magic",
        ]
    },
    {
        "name":"Exandria",
        "pre":"exandria",
        "gods":[ 
            "Avandra",
            "Bahamut",
            "Corellon",
            "Erathis",
            "Ioun",
            "Kord",
            "Melora",
            "Moradin",
            "Pelor",
            "Raei",
            "The Raven Queen",
            "Sehanine",
        ]
    },
    {
        "name":"Historical Pantheons",
        "pre":"historical",
        "gods":[ 
            "The Daghdha, god of weather and crops",
            "Arawn, god of life and death",
            "Belenus, god of sun, light, and warmth",
            "Brigantia, goddess of rivers and livestock",
            "Diancecht, god of medicine and healing",
            "Dunatis, god of mountains and peaks",
            "Goibhniu, god of smiths and healing",
            "Lugh, god of arts, travel, and commerce",
            "Manannan mac Lir, god of oceans and sea creatures",
            "Math Mathonwy, god of magic",
            "Morrigan, goddess of battle",
            "Nuada, god of war and warriors",
            "Oghma, god of speech and writing",
            "Silvanus, god of nature and forests",
            "Re-Horakhty, god of the sun, ruler of the gods",
            "Anubis, god of judgment and death",
            "Apep, god of evil, fire, and serpents",
            "Bast, goddess of cats and vengeance",
            "Bes, god of luck and music",
            "Hathor, goddess of love, music, and motherhood",
            "Imhotep, god of crafts and medicine",
            "Isis, goddess of fertility and magic",
            "Nephthys, goddess of death and grief",
            "Osiris, god of nature and the underworld",
            "Ptah, god of crafts, knowledge, and secrets",
            "Set, god of darkness and desert storms",
            "Sobek, god of water and crocodiles",
            "Thoth, god of knowledge and wisdom",
            "Zeus, god of the sky, ruler of the gods",
            "Aphrodite, goddess of love and beauty",
            "Apollo, god of light, music, and healing",
            "Ares, god of war and strife",
            "Artemis, goddess of hunting and childbirth",
            "Athena, goddess of wisdom and civilization",
            "Demeter, goddess of agriculture",
            "Dionysus, god of mirth and wine",
            "Hades, god of the underworld",
            "Hecate, goddess of magic and the moon",
            "Hephaestus, god of smithing and craft",
            "Hera, goddess of marriage and intrigue",
            "Hercules, god of strength and adventure",
            "Hermes, god of travel and commerce",
            "Hestia, goddess of home and family",
            "Nike, goddess of victory",
            "Pan, god of nature",
            "Poseidon, god of the sea and earthquakes",
            "Tyche, goddess of good fortune",
            "Odin, god of knowledge and war",
            "Aegir, god of the sea and storms",
            "Balder, god of beauty and poetry",
            "Forseti, god of justice and law",
            "Frey, god of fertility and the sun",
            "Freya, goddess of fertility and love",
            "Frigga, goddess of birth and fertility",
            "Heimdall, god of watchfulness and loyalty",
            "Hel, goddess of the underworld",
            "Hermod, god of luck",
            "Loki, god of thieves and trickery",
            "Njord, god of sea and wind",
            "Odur, god of light and the sun",
            "Sif, goddess of war",
            "Skadi, god of earth and mountains",
            "Surtur, god of fire giants and war",
            "Thor, god of storms and thunder",
            "Thrym, god of fire giants and cold",
            "Tyr, god of courage and strategy",
            "Uller, god of hunting and winter",
        ]
    }
];