const mentalConditions = [
    { "name":"Generalized Anxiety Disorder" },
{ "name":"Social Anxiety" },
{ "name":"Phobia","variations":[
    "heights",
    "flying",
    "spiders",
    "thunder and lightning",
    "being alone",
    "confined spaces",
    "blood",
    "water",
    "snakes",
    "animals",
    "dogs",
    "water",
    "needles",
    "flying",
    "public or crowded spaces",
    "insects",
    "public speaking",
    "illness",
    "darkness",
    "clowns",
    "vomiting",
    "fire"
] },
{ "name":"Panic Disorder" },
{ "name":"Bipolar Disorder" },
{ "name":"Depression" },
{ "name":"Seasonal Affective Disorder" },
{ "name":"Global Developmental Delay" },
{ "name":"Autism" },
{ "name":"ADHD" },
{ "name":"Acute Stress Disorder" },
{ "name":"Adjustment Disorder" },
{ "name":"PTSD" },
{ "name":"Dissociative Amnesia" },
{ "name":"Dissociative Identity Disorder" },
{ "name":"Depersonalization/Derealization Disorder" },
{ "name":"Somatic Symptom Disorder" },
{ "name":"Illness Anxiety" },
{ "name":"Conversion Disorder" },
{ "name":"Rumination Disorder" },
{ "name":"Pica" },
{ "name":"Avoidant-Restrictive Food Intake Disorder" },
{ "name":"Narcolepsy" },
{ "name":"Insomnia" },
{ "name":"Hypersomnolence" },
{ "name":"Parasomnia","variations":["sleepwalking","night terrors","sleep talking"] },
{ "name":"Restless Legs Syndrome" },
{ "name":"Kleptomania" },
{ "name":"Pyromania" },
{ "name":"Intermittent Explosive Disorder" },
{ "name":"Addiction","variations":["alcohol","stimulant","opioid","tabacco","gambling"] },
{ "name":"Schizophrenia" },
{ "name":"OCD" },
{ "name":"Body Dysmorphia" },
{ "name":"Hoarding Disorder" },
{ "name":"Trichotillomania" },
{ "name":"Excoriation (skin-picking)" },
{ "name":"Antisocial Personality Disorder" },
{ "name":"Avoidant Personality Disorder" },
{ "name":"Borderline Personality Disorder" },
{ "name":"Dependent Personality Disorder" },
{ "name":"Histrionic Personality Disorder" },
{ "name":"Narcissistic Personality Disorder" },
{ "name":"Obsessive-Compulsive Personality Disorder" },
{ "name":"Paranoid Personality Disorder" },
{ "name":"Schizoid Personality Disorder" },
{ "name":"Schizotypal Personality Disorder" },
{ "name":"Dementia" },
{ "name":"Dyslexia" },
{ "name":"Dyspraxia" },
{ "name":"Fetal Alcohol Syndrome" },
]
